#include "renders.h"
#include <omp.h>
#include <png.h>
#include <stdio.h>
#include <string.h>
#include <zlib.h>

#include <stdlib.h>

#include <colors.h>

#define displine printf("Line : %d\n", __LINE__);

bool exmaine_input(const char *const filename, const void *const data,
                   const int64_t rows, const int64_t cols) {
  if ((rows <= 0) || (cols <= 0)) {
    return false;
  }

  if (data == NULL) {
    return false;
  }

  if (filename == NULL || strlen(filename) <= 0) {
    return false;
  }

  return true;
}

bool create_structs(FILE **file, png_struct **png, png_info **info,
                    const char *const filename) {

  if (filename == NULL || strlen(filename) <= 0) {
    return false;
  }

  errno_t err = fopen_s(file, filename, "wb");

  if (*file == NULL) {
    printf("Failed to file struct of file %s, error number is %d.\n", filename,
           err);
    return false;
  }

  *png = png_create_write_struct(PNG_LIBPNG_VER_STRING, NULL, NULL, NULL);

  if (*png == NULL) {
    printf("Failed to create png_struct pointer.\n");
    return false;
  }

  *info = png_create_info_struct(*png);

  if (*info == NULL) {
    printf("Failed to create png_info.\n");
    return false;
  }

  return true;
}

bool write_png_u8c1(const void *const data, const size_t rows,
                    const size_t cols, const char *const filename) {

  if (!exmaine_input(filename, data, rows, cols))
    return false;

  FILE *file = NULL;
  png_struct *png = NULL;
  png_info *info = NULL;

  if (!create_structs(&file, &png, &info, filename)) {
    return false;
  }

  png_init_io(png, file);

  // png_set_filler(png, 0, PNG_FILTER_NONE);

  png_set_IHDR(png, info, cols, rows, 8, PNG_COLOR_TYPE_GRAY,
               PNG_INTERLACE_NONE, PNG_COMPRESSION_TYPE_DEFAULT,
               PNG_FILTER_TYPE_DEFAULT);
  png_set_compression_level(png, Z_BEST_COMPRESSION);
  /*
    {

      static const int text_num = 2;
      png_text texts[text_num];

      texts[0].text = "Fractal generated by libbunring_ship_renders.";
      texts[0].key = "Description";

      texts[1].key = "Author";
      texts[1].text = "libbunring_ship_renders";

      for (int idx = 0; idx < text_num; idx++) {
        texts[idx].text_length = strlen(texts[idx].text);
        texts[idx].itxt_length = texts[idx].text_length;
        texts[idx].compression = 0;
        texts[idx].lang = NULL;
        texts[idx].lang_key = NULL;
      }

      //png_set_text(png, info, texts, text_num);
    }
    */

  png_write_info(png, info);
  // png_write_png(png, info, PNG_TRANSFORM_IDENTITY, NULL);

  // png_write_image(png, row_pointers);
  const uint8_t *const datau8c1 = data;
  for (size_t r = 0; r < rows; r++) {
    png_write_row(png, datau8c1 + (r * cols));
  }

  png_write_end(png, info);

  png_destroy_write_struct(&png, &info);

  fclose(file);

  return true;
}

bool write_png_u8c1_rowptrs(const uint8_t *const *const u8c1_row_ptrs,
                            const size_t rows, const size_t cols,
                            const char *const filename) {

  if (!exmaine_input(filename, u8c1_row_ptrs, rows, cols))
    return false;

  FILE *file = NULL;
  png_struct *png = NULL;
  png_info *info = NULL;

  if (!create_structs(&file, &png, &info, filename)) {
    return false;
  }

  png_init_io(png, file);

  // png_set_filler(png, 0, PNG_FILTER_NONE);

  png_set_IHDR(png, info, cols, rows, 8, PNG_COLOR_TYPE_GRAY,
               PNG_INTERLACE_NONE, PNG_COMPRESSION_TYPE_DEFAULT,
               PNG_FILTER_TYPE_DEFAULT);
  png_set_compression_level(png, Z_BEST_COMPRESSION);

  png_write_info(png, info);
  // png_write_png(png, info, PNG_TRANSFORM_IDENTITY, NULL);

  // png_write_image(png, u8c1_row_ptrs);
  for (size_t r = 0; r < rows; r++) {
    png_write_row(png, u8c1_row_ptrs[r]);
  }

  png_write_end(png, info);

  png_destroy_write_struct(&png, &info);

  fclose(file);

  return true;
}

bool write_png_u8c3(const void *const data, const size_t rows,
                    const size_t cols, const char *const filename) {

  if (!exmaine_input(filename, data, rows, cols))
    return false;

  FILE *file = NULL;
  png_struct *png = NULL;
  png_info *info = NULL;

  if (!create_structs(&file, &png, &info, filename)) {
    return false;
  }

  png_init_io(png, file);

  // png_set_filler(png, 0, PNG_FILTER_NONE);

  png_set_IHDR(png, info, cols, rows, 8, PNG_COLOR_TYPE_RGB, PNG_INTERLACE_NONE,
               PNG_COMPRESSION_TYPE_DEFAULT, PNG_FILTER_TYPE_DEFAULT);
  png_set_compression_level(png, Z_BEST_COMPRESSION);

  png_write_info(png, info);
  // png_write_png(png, info, PNG_TRANSFORM_IDENTITY, NULL);

  // png_write_image(png, row_pointers);
  for (size_t r = 0; r < rows; r++) {

    png_write_row(png, (uint8_t *)data + r * cols * sizeof(pixel_u8c3));
  }

  png_write_end(png, info);

  png_destroy_write_struct(&png, &info);

  fclose(file);

  return true;
}