function [mat,rows,cols,bytes_per_float] = load_matrix(filename)

% load a file generated by burning_ship

    filename=string(filename);

    [pathstr,name,suffix]=fileparts(filename);

    if(strcmp(suffix,".gz"))
        % process .gz here

        inflated=gunzip(filename,"temp_load_matrix_please_dont_use");
        %disp(inflated)

        inflated=string(inflated{1});

        if(length(inflated)<=0)
            error("Failed to inflate file");
        end

        [mat,rows,cols,bytes_per_float]=load_matrix(inflated);

        delete(inflated);
        %error("Can't process .gz files yet");
        return;
    end

    


    fid=fopen(filename,"rb");

    if(fid<3)
        error(strcat("Failed to open file ",filename));
        return;
    end

    bytes_per_float=int8(fread(fid,1,"int8"));


    rows=int64(fread(fid,1,"int64"));
    cols=int64(fread(fid,1,"int64"));

    if(rows<=0||cols<=0) 
        error(strcat("Invalid matrix size : rows = ",num2str(rows),", cols = ",num2str(cols)));
        return;
    end

    
    if((bytes_per_float~=8)&&(~strcmp(suffix,".bs_frame")))
        error(strcat("Failed to analyze the matrix since the float precision is not 8 bytes but ",num2str(bytes_per_float)," bytes"));
    end



    if(strcmp(suffix,".bs_frame"))
        mat=int16(fread(fid,rows*cols,"int16"));
        mat=reshape(mat,[cols,rows])';
    end

    if(strcmp(suffix,".bs_norm2"))
        mat=fread(fid,rows*cols,"double");
        mat=reshape(mat,[cols,rows])';
    end

    if(strcmp(suffix,".bs_cplx_c3"))
        raw=fread(fid,rows*cols*3*2,"double");    % read in row-major
        mat=repmat(struct("c3",complex(zeros(1,3))),[rows,cols]);

        idx=1;
        for r=1:rows
            for c=1:cols
                for c_idx=1:3
                    mat(r,c).c3(c_idx)=raw(idx)+raw(idx+1)*1i;
                    idx=idx+2;
                end
            end
        end
    end


    fclose(fid);

    return;

end

